# Generated by Django 3.2.3 on 2021-05-25 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CamsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_unique_id', models.CharField(max_length=10, unique=True)),
                ('store_channel', models.IntegerField()),
                ('conf', models.IntegerField(default=25)),
                ('thresh', models.IntegerField(default=45)),
                ('snaps_path', models.TextField(default='/media/live/livedb/cams/Compliefile/C:/Store_Cam_picture/')),
                ('date', models.DateField(auto_now=True)),
                ('number_of_snaps', models.IntegerField(default=6)),
                ('hourly_api', models.BooleanField(default=True)),
                ('total_api', models.BooleanField(default=True)),
                ('device', models.CharField(choices=[('cpu', 'CPU'), (' ', 'GPU')], default=' ', max_length=4)),
                ('time', models.IntegerField(default=9)),
                ('status', models.BooleanField(default=True)),
                ('server_name', models.CharField(choices=[('Aiprod1', 'Aiprod1'), ('Aiprod2', 'Aiprod2'), ('Aiprod3', 'Aiprod3')], default='Aiprod1', max_length=15)),
            ],
            options={
                'db_table': 'camsdata',
            },
        ),
        migrations.CreateModel(
            name='MainSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_for_all_store', models.CharField(max_length=10)),
                ('path_for_all_store', models.CharField(default='/media/live/livedb/cams/Compliefile/C:/Store_Cam_picture/', max_length=255)),
                ('device', models.CharField(default='', max_length=10)),
                ('source_weight', models.CharField(default='', max_length=50)),
                ('hourly_api_for_all_store_live', models.BooleanField(default=True)),
                ('total_api_for_all_store_live', models.BooleanField(default=True)),
                ('api_for_all_store_local', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'mainsetting',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'market',
            },
        ),
        migrations.CreateModel(
            name='StoresStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'storestatus',
            },
        ),
        migrations.CreateModel(
            name='MisTrafficCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField()),
                ('hourly_count', models.IntegerField()),
                ('time', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=20)),
                ('conf', models.IntegerField()),
                ('thresh', models.IntegerField()),
                ('number_of_snaps', models.IntegerField()),
                ('store_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camsconfig.camsdata')),
            ],
            options={
                'db_table': 'mistrafficcount',
            },
        ),
        migrations.AddField(
            model_name='camsdata',
            name='current_status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='camsconfig.storesstatus'),
        ),
        migrations.AddField(
            model_name='camsdata',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camsconfig.market'),
        ),
        migrations.CreateModel(
            name='ManualCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camsconfig.market')),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camsconfig.camsdata')),
            ],
            options={
                'db_table': 'manualcount',
                'unique_together': {('store_name', 'date')},
            },
        ),
    ]
