# Generated by Django 3.2.3 on 2021-05-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsetting',
            name='is_system_date',
            field=models.BooleanField(default=True),
        ),
    ]
