# Generated by Django 3.2.3 on 2021-05-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camsconfig', '0002_mainsetting_is_system_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camsdata',
            name='server_name',
            field=models.CharField(choices=[('Aiprod1', 'Aiprod1'), ('Aiprod2', 'Aiprod2'), ('Aiprod3', 'Aiprod3')], default='Aiprod2', max_length=15),
        ),
        migrations.AlterField(
            model_name='camsdata',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Active / Deactive'),
        ),
    ]
